---
apiVersion: v1
kind: ConfigMap
metadata:
  name: emqx-config
  namespace: {{ include "emqx.ns" . }}
  labels:
    app: emqx
data:
{{- range $key, $value := .Values.emqx.config }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
