---
# PVC for EMQX runtime data (rules, auth, mnesia)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emqx-data
  namespace: {{ include "emqx.ns" . }}
  labels:
    app: emqx
  {{- include "emqx.keepAnnotations" . | nindent 2 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ include "emqx.storageClass" (list . .Values.emqx.persistence.data.storageClassName) }}
  resources:
    requests:
      storage: {{ .Values.emqx.persistence.data.size }}
---
# PVC for EMQX runtime logs
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emqx-log
  namespace: {{ include "emqx.ns" . }}
  labels:
    app: emqx
  {{- include "emqx.keepAnnotations" . | nindent 2 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ include "emqx.storageClass" (list . .Values.emqx.persistence.log.storageClassName) }}
  resources:
    requests:
      storage: {{ .Values.emqx.persistence.log.size }}
