---
apiVersion: v1
kind: Secret
metadata:
  name: emqx-secret
  namespace: {{ .Values.namespace.name }}
  labels:
    app: emqx
type: Opaque
stringData:
  EMQX_DASHBOARD__DEFAULT_USERNAME: {{ .Values.secrets.dashboardUsername | quote }}
  EMQX_DASHBOARD__DEFAULT_PASSWORD: {{ .Values.secrets.dashboardPassword | quote }}
